---
apiVersion: v2
name: matrix-synapse
description: Matrix reference homeserver
icon: https://matrix.org/images/matrix-logo.svg
appVersion: 1.77.0

type: application
version: 3.1.1
maintainers:
  - name: Alexander Olofsson
    email: ace@haxalot.com

dependencies:
  - name: postgresql
    version: ^12.2.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: ^17.7.5
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
